import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import AOSInit from "./AOSInit";
import Header from "./components/header";
import { CartProvider } from "./components/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const baiJamjuree = localFont({
  src: "./fonts/BaiJamjuree-Regular.ttf",
});

const spaceGrotesk = localFont({
  src: "./fonts/SpaceGrotesk-Regular.ttf",
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <Header />
          <AOSInit />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
